---

# id_rsa file is synced with iCloud
- name: Create ssh directory
  file:
    path: "{{ home_dir }}/.ssh"
    mode: 0700
    state: directory

- name: Create symbolic link to id_rsa
  file:
    src: "{{ home_dir }}/Documents/Dotfiles/ssh/id_rsa"
    dest: "{{ home_dir }}/.ssh/id_rsa"
    state: link

- name: Create symbolic link to id_rsa.pub
  file:
    src: "{{ home_dir }}/Documents/Dotfiles/ssh/id_rsa.pub"
    dest: "{{ home_dir }}/.ssh/id_rsa.pub"
    state: link
