#!/bin/zsh

if [ "$(uname)" != "Darwin" ] ; then
  echo "Not macOS!"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install packages with Homebrew
brew bundle

# Setup Git
ln -fnsv "${SCRIPT_DIR}/git/gitconfig" "$HOME/.gitconfig"
ln -fnsv "${SCRIPT_DIR}/git/gitignore" "$HOME/.gitignore"

# Setup Vim
ln -fnsv "${SCRIPT_DIR}/vim/vimrc" "$HOME/.vimrc"
