#! /usr/bin/env sh

set -eux

DOTFILES_DIR=$(dirname "$0")

if [ ! -e ~/.zprezto ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

  setopt EXTENDED_GLOB
  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  done
fi

mkdir -p ~/.git
cp $DOTFILES_DIR/git/ignore ~/.git/.ignore
cp $DOTFILES_DIR/gitconfig ~/.gitconfig
cp $DOTFILES_DIR/zshrc ~/.zshrc

sudo chsh $(whoami) -s $(which zsh)
