#!/bin/zsh

if [ "$(uname)" != "Darwin" ] ; then
  echo "Not macOS!"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

#
# Install Homebrew
#
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

#
# Install packages with Homebrew
#
brew bundle

#
# Setup Git
#
ln -fnsv "${SCRIPT_DIR}/git/gitconfig" "$HOME/.gitconfig"
ln -fnsv "${SCRIPT_DIR}/git/gitignore" "$HOME/.gitignore"
mkdir -p "$HOME/.vim/colors"
git clone https://github.com/tomasr/molokai.git

#
# Setup Vim
#
ln -fnsv "${SCRIPT_DIR}/vim/vimrc" "$HOME/.vimrc"

#
# Setup https://github.com/peco/peco
#
mkdir -p "$HOME/.config/peco"
ln -fnsv "${SCRIPT_DIR}/peco/config.json" "$HOME/.config/peco/config.json"

#
# Setup macOS Defaults
#
# Disabled Dashboard
defaults write com.apple.dashboard mcx-disabled -bool true
# Show all files
defaults write com.apple.finder AppleShowAllFiles -bool true
# Show all extensions
defaults write com.apple.finder AppleShowAllExtensions -bool true

#
# Setup Zsh and https://github.com/sorin-ionescu/prezto
#
PREZTO_INSTALL_DEST="${ZDOTDIR:-$HOME}/.zprezto"
if [ ! -d "${PREZTO_INSTALL_DEST}" ];then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${PREZTO_INSTALL_DEST}"
fi
ln -fnsv "${SCRIPT_DIR}/zsh/zshconfig" "$HOME/.zshconfig"

echo -e "\nInstall Finished!\n"
