tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "jwbargsten/misc"
brew "cask"
brew "gh"
brew "ghq"
brew "hugo"
brew "jq"
brew "mas"
brew "peco"
brew "php"
brew "tig"
brew "tree"
brew "vim"
brew "wget"
cask "1password"
cask "alfred"
cask "cleanmymac"
cask "dash"
cask "font-cica"
cask "iterm2"
cask "kindle"
cask "visual-studio-code"
cask "zoom"
mas "Day One", id: 1055511498
mas "feedly", id: 865500966
mas "Keepa - Price Tracker", id: 1533805339
mas "Magnet", id: 441258766
mas "Things", id: 904280696
