tap "c-bata/kube-prompt"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "jwbargsten/misc"
brew "awscli"
brew "cask"
brew "gh"
brew "ghq"
brew "hugo"
brew "jq"
brew "mas"
brew "peco"
brew "php"
brew "tig"
brew "tree"
brew "vim"
brew "wget"
brew "c-bata/kube-prompt/kube-prompt"
cask "1password"
cask "alfred"
cask "choosy"
cask "dash"
cask "docker"
cask "font-cica"
cask "google-chrome"
cask "iterm2"
cask "jasper"
cask "kindle"
cask "logitech-options"
cask "logitech-unifying"
cask "microsoft-teams"
cask "sf-symbols"
cask "skitch"
cask "slack"
cask "visual-studio-code"
cask "zoom"
mas "Dato", id: 1470584107
mas "Day One", id: 1055511498
mas "feedly", id: 865500966
mas "Keepa - Price Tracker", id: 1533805339
mas "Magnet", id: 441258766
mas "Things", id: 904280696
