---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - homebrew
    - homebrew_cask
    - setup_git
    - setup_ssh
    - setup_vim
    - setup_zsh
    - setup_peco
    - macos
  vars:
    # execution user vars
    - home_dir: "{{ lookup('env', 'HOME') }}"
