- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - homebrew
    - homebrew-cask
    - mas
    - setup-git
    - setup-ssh
  vars:
    # mas role
    - install_mas: "no"
