---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - homebrew
    - homebrew_cask
    - setup_git
    - setup_ssh
    - setup_vim
    - setup_zsh
    - setup_peco
    - inkdrop_plugins
    - macos
  vars:
    # execution user vars
    - home_dir: "{{ lookup('env', 'HOME') }}"
    # inkdrop-plugins role
    # yamllint disable-line rule:line-length
    - inkdrop_packages_dir: "{{ home_dir }}/Library/Application\ Support/inkdrop/packages"
