---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  roles:
    - homebrew
    - homebrew-cask
    - setup-git
    - setup-ssh
    - setup-vim
    - setup-zsh
    - setup-peco
    - inkdrop-plugins
    - macos
    - aaaa
  vars:
    # execution user vars
    - home_dir: "{{ lookup('env', 'HOME') }}"
    # inkdrop-plugins role
    # yamllint disable-line rule:line-length
    - inkdrop_packages_dir: "{{ home_dir }}/Library/Application\ Support/inkdrop/packages"
