---
- name: Install Homebrew Cask
  homebrew:
    name: cask
    state: present

- name: Install Homebrew Cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - alfred
    - android-studio
    - dash
    - docker
    - firefox
    - google-chrome
    - google-japanese-ime
    - inkdrop
    - iterm2
    - rescuetime
    - sketch
