---

- name: Make .vim directory
  file:
    path: "{{ home_dir }}/.vim"
    state: directory

- name: Make .vim colors directory
  file:
    path: "{{ home_dir }}/.vim/colors"
    state: directory

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: "{{ home_dir }}/.vimrc"
    force: true
    mode: '0644'

- name: Copy vim theme file
  copy:
    src: molokai.vim
    dest: "{{ home_dir }}/.vim/colors/molokai.vim"
    force: true
    mode: '0644'

- name: Make vim plugin directory
  file:
    path: "{{ home_dir }}/.vim/autoload"
    state: directory

- name: Download vim-plug file
  get_url:
    dest: "{{ home_dir }}/.vim/autoload/plug.vim"
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
