---

# .gitconfig file is synced with iCloud
- name: Create symbolic link to .gitconfig
  file:
    src: "{{ home_dir }}/Documents/Dotfiles/gitconfig"
    dest: "{{ home_dir }}/.gitconfig"
    state: link
