---
- name: Update and Upgrade Homebrew
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Install Homebrew packages
  community.general.homebrew:
    name:
      - awscli
      - ghq
      - git-flow-avh
      - hugo
      - jq
      - peco
      - php
      - tig
      - tree
      - vim
      - wget
    state: present
