---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install Homebrew packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - git-flow-avh
    - jq
    - mas
    - tig
    - tree
    - wget
