---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Tap heroku repository
  homebrew_tap:
    name: heroku/brew
    state: present

- name: Install Homebrew packages
  homebrew:
    name: ['awscli', 'carthage', 'ghq', 'git-flow-avh', 'heroku', 'hub', 'jq', 'peco', 'stern', 'tig', 'tree', 'vim', 'wget']
    state: present
