---
- name: Update and Upgrade Homebrew
  community.general.homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Tap heroku repository
  homebrew_tap:
    name: heroku/brew
    state: present

- name: Install Homebrew packages
  community.general.homebrew:
    name:
      - awscli
      - bluetoothconnector
      - firebase-cli
      - gh
      - ghq
      - git-flow-avh
      - git-secrets
      - heroku
      - hugo
      - jq
      - peco
      - tig
      - tree
      - vim
      - wget
    state: present
