---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install Homebrew packages
  homebrew:
    name: ['carthage', 'git-flow-avh', 'jq', 'tig', 'tree', 'vim', 'wget']
    state: present
