---

- name: Make .vim directory
  file:
    path: ~/.vim
    state: directory

- name: Make .vim colors directory
  file:
    path: ~/.vim/colors
    state: directory

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: ~/.vimrc
    force: yes

- name: Copy vim theme file
  copy:
    src: molokai.vim
    dest: ~/.vim/colors/molokai.vim
    force: yes

- name: Make vim plugin directory
  file:
    path: ~/.vim/autoload
    state: directory

- name: Download vim-plug file
  get_url:
    dest: ~/.vim/autoload/plug.vim
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
