---

- name: Install prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: "{{ home_dir }}/.zprezto"
    update: no

- name: Add symbolic link dotfiles
  file:
    src: "{{ home_dir }}/.zprezto/runcoms/{{ item }}"
    dest: "{{ home_dir }}/.{{ item }}"
    state: link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc

- name: Add symbolic link to config directory on iCloud
  file:
    src: "{{ home_dir }}/Documents/Dotfiles/zshconfig"
    dest: "{{ home_dir }}/.zshconfig"
    state: link
