---
- name: Install Homebrew Cask
  homebrew:
    name: cask
    state: present

- name: Tap DevHub repository
  homebrew_tap:
    name: devhubapp/devhub
    state: present

- name: Tap homebrew/cask-fonts
  homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install Homebrew Cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - 1password
    - alfred
    - appcleaner
    - dash
    - devhub
    - docker
    - font-cica
    - google-chrome
    - inkdrop
    - intellij-idea
    - iterm2
    - kindle
    - sequel-pro
    - sf-symbols
    - skitch
    - slack
    - toggl-track
