---

- name: Tap for ricty
  homebrew_tap:
    tap: sanemat/font
    state: present

- name: Install ricty
  homebrew:
    name: ricty
    state: latest
    install_options: with-powerline,vim-powerline

- name: Copy fonts
  copy:
    src: "{{ item }}"
    dest: ~/Library/Fonts/
  with_fileglob:
    - "/usr/local/opt/ricty/share/fonts/Ricty*.ttf"
  notify: run fc-cache

- name: Create symbolic link to iTerm2 setting file
  file:
    src: ~/Documents/Application\ Datas/iTerm2/com.googlecode.iterm2.plist
    dest: ~/Library/Preferences/com.googlecode.iterm2.plist
    state: link
    force: yes
